version: 0.2

phases:

  install:
    runtime-versions:
      ruby: 3.2.8
  build:
    on-failure: ABORT
    commands:
      - ruby -v
      - bundle install
      - bundle exec rdoc lib/*.rb
      - rm -rf api/uc3-ssm
      - mkdir -p api/uc3-ssm/ruby
      - cp -r doc/* api/uc3-ssm/ruby
      - echo aws s3 cp --recursive api s3://${S3CFBUCKET}/api 
      - aws s3 cp --recursive api s3://${S3CFBUCKET}/api
      - aws cloudfront create-invalidation --distribution-id ${CFDISTRIBUTIONID} --paths /* --region us-east-1
